name: RUDIVERSE
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
      type: "quizzes"
    values:
      layout: "quiz"
  - scope:
      path: ""
      type: "quotes"
    values:
      layout: "quote"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "languages"
    values:
      layout: "language"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  quizzes:
    output: true
  quotes:
    output: true